/* eslint-disable import/prefer-default-export */

const actions = {
  SET_RUNTIME_VARIABLE: 'SET_RUNTIME_VARIABLE',
  SET_CURRENT_PLATE: 'SET_CURRENT_PLATE',
  IMPORT_FILE: 'IMPORT_FILE',
  SET_PENDING_PLATES_TABLE: 'SET_PENDING_PLATES_TABLE',
  ADD_BATCH_PENDING_PLATES_TABLE: 'ADD_BATCH_PENDING_PLATES_TABLE',
  SET_VERIFIED_PLATES_TABLE: 'SET_VERIFIED_PLATES_TABLE',
  ADD_BATCH_VERIFIED_PLATES_TABLE: 'ADD_BATCH_VERIFIED_PLATES_TABLE',
  SET_REMOVED_PLATES_TABLE: 'SET_REMOVED_PLATES_TABLE',
  ADD_BATCH_REMOVED_PLATES_TABLE: 'ADD_BATCH_REMOVED_PLATES_TABLE',
  SET_POSTPONED_PLATES_TABLE: 'SET_POSTPONED_PLATES_TABLE',
  ADD_BATCH_POSTPONED_PLATES_TABLE: 'ADD_BATCH_POSTPONED_PLATES_TABLE',
  ADD_PENDING_PLATE: 'ADD_PENDING_PLATE',
  REMOVE_REJECTED_PLATE: 'REMOVE_REJECTED_PLATE',
  REMOVE_POSTPONED_PLATE: 'REMOVE_POSTPONED_PLATE',
};

export default actions;
